language: node_js

node_js: stable

cache:
  directories:
    - node_modules

before_install:
  - npm install hexo-cli -g

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - cp CNAME ./public/CNAME
  - cd ./public
  - git init
  - git config user.name "LiwenHao"
  - git config user.email "wenhao0714@gmail.com"
  - git add .
  - git commit -m "Travis CI Auto Builder..."
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" HEAD:master

branches:
  only:
    - hexo
env:
 global:
   - GH_REF: github.com/27392/27392.github.io.git